"""Constants for interactive Assistant pending action plans."""

PENDING_ACTION_PLAN_TTL_SECONDS = 30 * 60
MAX_ACTIONS_PER_PLAN = 5

PENDING_ACTION_PLAN_STATUS_PENDING = "pending"
PENDING_ACTION_PLAN_STATUS_EXECUTED = "executed"
PENDING_ACTION_PLAN_STATUS_REJECTED = "rejected"
PENDING_ACTION_PLAN_STATUS_EXPIRED = "expired"
PENDING_ACTION_PLAN_STATUS_FAILED = "failed"
