from datetime import timedelta

from app.jobs.constants import JOB_TYPE_PROACTIVE_REVIEW

__all__ = [
    "JOB_TYPE_PROACTIVE_REVIEW",
    "NOTIFICATION_KIND_INSIGHT",
    "NOTIFICATION_KIND_TASK_PROPOSAL",
    "PROACTIVE_ENABLED_DEFAULT",
    "PROACTIVE_EVENT_HORIZON",
    "PROACTIVE_EVENT_KINDS",
    "PROACTIVE_FAILED_REARM_SECONDS",
    "PROACTIVE_GATE_ORIGINS",
    "PROACTIVE_INTERVAL_MINUTES_DEFAULT",
    "PROACTIVE_INTERVAL_MINUTES_MAX",
    "PROACTIVE_INTERVAL_MINUTES_MIN",
    "PROACTIVE_MAX_OUTPUT_TOKENS",
    "PROACTIVE_MAX_ROUNDS",
    "PROACTIVE_MAX_TOOL_CALLS",
    "PROACTIVE_MAX_UNRESOLVED",
    "PROACTIVE_MIN_CONFIDENCE",
    "PROACTIVE_PERSONAL_RELEVANCE_EVENT",
    "PROACTIVE_READ_TOOL_NAMES",
    "PROACTIVE_SEED_OBJECT_LIMIT",
    "PROACTIVE_SIGNATURE_COOLDOWN",
    "PROACTIVE_SIGNATURE_VERSION",
    "PROACTIVE_TASK_HORIZON",
    "PROACTIVE_TASK_LOOKBACK",
    "PROPOSAL_TYPE_PROACTIVE_INSIGHT",
    "PROPOSAL_TYPE_TASK",
    "STALE_FENCE_INCOMPLETE",
    "STALE_FENCE_NOT_APPLICABLE",
    "STALE_FENCE_STALE",
    "STALE_FENCE_UNCHANGED",
]


PROACTIVE_ENABLED_DEFAULT = False
PROACTIVE_INTERVAL_MINUTES_DEFAULT = 60
PROACTIVE_INTERVAL_MINUTES_MIN = 15
PROACTIVE_INTERVAL_MINUTES_MAX = 1440

PROACTIVE_MAX_UNRESOLVED = 3
PROACTIVE_MAX_TOOL_CALLS = 6
PROACTIVE_MAX_ROUNDS = 4
PROACTIVE_MAX_OUTPUT_TOKENS = 800
PROACTIVE_MIN_CONFIDENCE = 0.75
PROACTIVE_SIGNATURE_VERSION = 1
PROACTIVE_SIGNATURE_COOLDOWN = timedelta(hours=24)
PROACTIVE_FAILED_REARM_SECONDS = 3600

PROACTIVE_TASK_LOOKBACK = timedelta(days=7)
PROACTIVE_TASK_HORIZON = timedelta(hours=24)
PROACTIVE_EVENT_HORIZON = timedelta(hours=24)
PROACTIVE_EVENT_KINDS = ("event", "calendar_event")

PROACTIVE_SEED_OBJECT_LIMIT = 20

PROACTIVE_READ_TOOL_NAMES = (
    "retrieve",
    "query_objects",
    "get_object",
    "get_context",
    "list_neighbors",
    "list_notifications",
)

PROACTIVE_GATE_ORIGINS = frozenset({"source", "explicit", "user"})

PROPOSAL_TYPE_PROACTIVE_INSIGHT = "proactive_insight"
PROPOSAL_TYPE_TASK = "task"

NOTIFICATION_KIND_INSIGHT = "insight"
NOTIFICATION_KIND_TASK_PROPOSAL = "task_proposal"

PROACTIVE_PERSONAL_RELEVANCE_EVENT = "proactive_personal_relevance"
STALE_FENCE_UNCHANGED = "unchanged"
STALE_FENCE_STALE = "stale"
STALE_FENCE_INCOMPLETE = "incomplete"
STALE_FENCE_NOT_APPLICABLE = "not_applicable"
