MAX_JOB_ATTEMPTS = 3
STALE_LOCK_MINUTES = 15
MAX_LAST_ERROR_LENGTH = 1000
WORKER_IDLE_SLEEP_SECONDS = 2
SCHEDULER_MAINTENANCE_INTERVAL_SECONDS = 60

JOB_STATUS_PENDING = "pending"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_DONE = "done"
JOB_STATUS_FAILED = "failed"

JOB_TYPE_EMBED_OBJECT = "embed_object"
JOB_TYPE_INGEST_LOCAL_FILE = "ingest_local_file"
JOB_TYPE_SUMMARIZE_RESOURCE = "summarize_resource"
JOB_TYPE_SUMMARIZE_CONVERSATION_STACK = "summarize_conversation_stack"
JOB_TYPE_EXTRACT_EXPLICIT_RESOURCE_CONTENT = "extract_explicit_resource_content"
JOB_TYPE_CORRELATE_OBJECT = "correlate_object"
JOB_TYPE_AUTO_LABEL_OBJECT = "auto_label_object"
JOB_TYPE_EXTRACT_TEMPORAL_SIGNAL = "extract_temporal_signal"
JOB_TYPE_RECONCILE_TEMPORAL_HINTS = "reconcile_temporal_hints"

JOB_TYPE_SYNC_GOOGLE_GMAIL = "sync_google_gmail"
JOB_TYPE_SYNC_GOOGLE_CALENDAR = "sync_google_calendar"
JOB_TYPE_SYNC_YANDEX_MAIL = "sync_yandex_mail"
JOB_TYPE_SYNC_YANDEX_CALENDAR = "sync_yandex_calendar"
JOB_TYPE_SYNC_MATTERMOST = "sync_mattermost"
JOB_TYPE_SYNC_TEAMS = "sync_teams"
JOB_TYPE_SYNC_TELEGRAM_MTPROTO = "sync_telegram_mtproto"
JOB_TYPE_PROCESS_TEAMS_NOTIFICATION = "process_teams_notification"
JOB_TYPE_RUN_SCHEDULED_ACTIVITY = "run_scheduled_activity"
JOB_TYPE_PROACTIVE_REVIEW = "proactive_review"

RECURRING_SOURCE_JOB_TYPES = frozenset(
    {
        JOB_TYPE_SYNC_GOOGLE_GMAIL,
        JOB_TYPE_SYNC_GOOGLE_CALENDAR,
        JOB_TYPE_SYNC_YANDEX_MAIL,
        JOB_TYPE_SYNC_YANDEX_CALENDAR,
        JOB_TYPE_SYNC_MATTERMOST,
        JOB_TYPE_SYNC_TEAMS,
        JOB_TYPE_SYNC_TELEGRAM_MTPROTO,
    }
)

WORKER_SCHEDULED_LANE_TYPES = frozenset({JOB_TYPE_RUN_SCHEDULED_ACTIVITY})
WORKER_SOURCE_SYNC_LANE_TYPES = RECURRING_SOURCE_JOB_TYPES
WORKER_GENERAL_EXCLUDE_TYPES = frozenset(
    {*WORKER_SCHEDULED_LANE_TYPES, *WORKER_SOURCE_SYNC_LANE_TYPES, JOB_TYPE_PROCESS_TEAMS_NOTIFICATION}
)
WORKER_TEAMS_NOTIFICATION_LANE_TYPES = frozenset({JOB_TYPE_PROCESS_TEAMS_NOTIFICATION})


def teams_notification_lane_job_types() -> tuple[str, ...]:
    return tuple(sorted(WORKER_TEAMS_NOTIFICATION_LANE_TYPES))


def source_sync_lane_job_types() -> tuple[str, ...]:
    return tuple(sorted(WORKER_SOURCE_SYNC_LANE_TYPES))

SOURCE_SYNC_INTERVAL_SECONDS = {
    JOB_TYPE_SYNC_GOOGLE_GMAIL: 120,
    JOB_TYPE_SYNC_YANDEX_MAIL: 120,
    JOB_TYPE_SYNC_GOOGLE_CALENDAR: 300,
    JOB_TYPE_SYNC_YANDEX_CALENDAR: 300,
    JOB_TYPE_SYNC_MATTERMOST: 120,
    JOB_TYPE_SYNC_TEAMS: 900,
    JOB_TYPE_SYNC_TELEGRAM_MTPROTO: 60,
}

RECURRING_FAILED_REARM_SECONDS = 3600

RETRY_BACKOFF_SECONDS = {
    1: 10,
    2: 60,
}
