"""Shared source-key and recurring job-type mappings."""

from app.jobs.constants import (
    JOB_TYPE_SYNC_GOOGLE_CALENDAR,
    JOB_TYPE_SYNC_GOOGLE_GMAIL,
    JOB_TYPE_SYNC_MATTERMOST,
    JOB_TYPE_SYNC_TEAMS,
    JOB_TYPE_SYNC_YANDEX_CALENDAR,
    JOB_TYPE_SYNC_YANDEX_MAIL,
)

SOURCE_GMAIL = "gmail"
SOURCE_GOOGLE_CALENDAR = "google_calendar"
SOURCE_YANDEX_MAIL = "yandex_mail"
SOURCE_YANDEX_CALENDAR = "yandex_calendar"
SOURCE_MATTERMOST = "mattermost"
SOURCE_TEAMS = "teams"

SUPPORTED_SOURCE_KEYS: frozenset[str] = frozenset(
    {
        SOURCE_GMAIL,
        SOURCE_GOOGLE_CALENDAR,
        SOURCE_YANDEX_MAIL,
        SOURCE_YANDEX_CALENDAR,
        SOURCE_MATTERMOST,
        SOURCE_TEAMS,
    }
)

SUPPORTED_SOURCE_KEYS_ORDERED: tuple[str, ...] = (
    SOURCE_GMAIL,
    SOURCE_GOOGLE_CALENDAR,
    SOURCE_YANDEX_MAIL,
    SOURCE_YANDEX_CALENDAR,
    SOURCE_MATTERMOST,
    SOURCE_TEAMS,
)

JOB_TYPE_TO_SOURCE: dict[str, str] = {
    JOB_TYPE_SYNC_GOOGLE_GMAIL: SOURCE_GMAIL,
    JOB_TYPE_SYNC_GOOGLE_CALENDAR: SOURCE_GOOGLE_CALENDAR,
    JOB_TYPE_SYNC_YANDEX_MAIL: SOURCE_YANDEX_MAIL,
    JOB_TYPE_SYNC_YANDEX_CALENDAR: SOURCE_YANDEX_CALENDAR,
    JOB_TYPE_SYNC_MATTERMOST: SOURCE_MATTERMOST,
    JOB_TYPE_SYNC_TEAMS: SOURCE_TEAMS,
}

SOURCE_TO_JOB_TYPE: dict[str, str] = {
    source: job_type for job_type, source in JOB_TYPE_TO_SOURCE.items()
}
