"""Canonical AI workload and trace event types for PHASE 28D-A observability."""

from datetime import timedelta

# Workloads
WORKLOAD_ASSISTANT_INTERACTIVE = "assistant_interactive"
WORKLOAD_ASSISTANT_ACTION_PLAN_FINALIZE = "assistant_action_plan_finalize"
WORKLOAD_BACKGROUND_SUMMARY = "background_summary"
WORKLOAD_BACKGROUND_CORRELATION = "background_correlation"
WORKLOAD_EMBEDDING = "embedding"
WORKLOAD_TRANSCRIPTION = "transcription"
WORKLOAD_SPEECH = "speech"
WORKLOAD_BACKGROUND_PROACTIVE_REVIEW = "background_proactive_review"
WORKLOAD_BACKGROUND_AUTO_LABEL = "background_auto_label"
WORKLOAD_BACKGROUND_TEMPORAL_SIGNAL = "background_temporal_signal"

WORKLOADS = frozenset(
    {
        WORKLOAD_ASSISTANT_INTERACTIVE,
        WORKLOAD_ASSISTANT_ACTION_PLAN_FINALIZE,
        WORKLOAD_BACKGROUND_SUMMARY,
        WORKLOAD_BACKGROUND_CORRELATION,
        WORKLOAD_EMBEDDING,
        WORKLOAD_TRANSCRIPTION,
        WORKLOAD_SPEECH,
        WORKLOAD_BACKGROUND_PROACTIVE_REVIEW,
        WORKLOAD_BACKGROUND_AUTO_LABEL,
        WORKLOAD_BACKGROUND_TEMPORAL_SIGNAL,
    }
)

# Event types
EVENT_TRACE_STARTED = "trace_started"
EVENT_MODEL_ROUND = "model_round"
EVENT_MODEL_ROUND_FAILED = "model_round_failed"
EVENT_TOOL_CALL = "tool_call"
EVENT_TRACE_FINISHED = "trace_finished"

# Capture session bounds
DEFAULT_CAPTURE_DURATION_MINUTES = 60
MAX_CAPTURE_DURATION_MINUTES = 120
PAYLOAD_RETENTION_AFTER_CAPTURE_HOURS = 48
METADATA_RETENTION_DAYS = 90

DEFAULT_CAPTURE_DURATION = timedelta(minutes=DEFAULT_CAPTURE_DURATION_MINUTES)
PAYLOAD_RETENTION_AFTER_CAPTURE = timedelta(hours=PAYLOAD_RETENTION_AFTER_CAPTURE_HOURS)
METADATA_RETENTION = timedelta(days=METADATA_RETENTION_DAYS)

# Query limits
MAX_TRACE_LIST = 100
MAX_EVENTS_PER_TRACE = 500
MAX_SUMMARY_RANGE_DAYS = 31

# Payload bounds
MAX_STORED_PAYLOAD_CHARS = 32000
