AUTO_LABEL_ENABLED_DEFAULT = False
AUTO_LABEL_VERSION = 2
AUTO_LABEL_MAX_TITLE_CHARS = 500
AUTO_LABEL_MAX_CONTENT_CHARS = 4000
AUTO_LABEL_MAX_OUTPUT_TOKENS = 600
AUTO_LABEL_MAX_RATIONALE_CHARS = 300
AUTO_LABEL_MAX_ASSIGNMENTS = 5
AUTO_LABEL_MIN_CONFIDENCE = 0.85
AUTO_LABEL_MAX_VOCABULARY = 200
AUTO_LABEL_MAX_PENDING_PER_USER = 32
MAX_PERSONAL_SEMANTIC_CONTEXT_CHARS = 6000
AUTO_LABEL_MAX_IDENTITY_ROLES = 12
AUTO_LABEL_MAX_IDENTITY_ORGANIZATIONS = 12
AUTO_LABEL_MAX_IDENTITY_ITEM_CHARS = 160

AUTO_LABEL_ELIGIBLE_ORIGINS = frozenset({"user", "source", "explicit"})

ANNOTATION_SOURCE_BACKGROUND_AUTO_LABEL = "background_auto_label"
METADATA_ANNOTATION_SOURCE = "annotation_source"
METADATA_AUTO_LABEL_VERSION = "auto_label_version"
METADATA_AUTO_LABEL_SIGNATURE = "auto_label_signature"
METADATA_RATIONALE = "rationale"

PARENT_EMAIL_ID_KEY = "parent_email_id"
