from datetime import timedelta

TEMPORAL_SIGNALS_ENABLED_DEFAULT = False
TEMPORAL_SIGNAL_EXTRACTOR_VERSION = 1
TEMPORAL_SIGNAL_METADATA_VERSION = 1

TEMPORAL_SIGNAL_MAX_TITLE_CHARS = 240
TEMPORAL_SIGNAL_MAX_BODY_CHARS = 4000
TEMPORAL_SIGNAL_MAX_EXTRACTED_TITLE_CHARS = 120
TEMPORAL_SIGNAL_MAX_SEMANTIC_SUBJECT_CHARS = 200
TEMPORAL_SIGNAL_MAX_OUTPUT_TOKENS = 800
TEMPORAL_SIGNAL_MAX_CANDIDATES = 8
TEMPORAL_SIGNAL_MAX_EVIDENCE_EDGES_SCAN = 64
TEMPORAL_SIGNAL_REASONING_EFFORT = "low"
TEMPORAL_SIGNAL_VERBOSITY = "low"
TEMPORAL_SIGNAL_AUDIT_EXTRACT = "temporal_extract"
TEMPORAL_SIGNAL_AUDIT_MATCH = "temporal_match"
TEMPORAL_SIGNAL_AUDIT_RECONCILE_MATCH = "temporal_reconcile_match"

TEMPORAL_SIGNAL_HORIZON_DAYS = 30
TEMPORAL_SIGNAL_MAX_DURATION = timedelta(hours=24)
TEMPORAL_SIGNAL_MIN_DURATION = timedelta(minutes=1)
TEMPORAL_SIGNAL_CANDIDATE_WINDOW = timedelta(hours=2)
TEMPORAL_SIGNAL_START_PROXIMITY = timedelta(minutes=30)

TEMPORAL_SIGNAL_MATCH_MIN_CONFIDENCE = 0.90
TEMPORAL_SIGNAL_EXPECTED_MIN_CONFIDENCE = 0.75
TEMPORAL_SIGNAL_POSSIBLE_MIN_CONFIDENCE = 0.90

TEMPORAL_ELIGIBLE_KINDS = frozenset({"email", "chat_message"})
TEMPORAL_ELIGIBLE_PROVIDERS = frozenset(
    {"gmail", "yandex_mail", "mattermost", "telegram", "teams"}
)
TEMPORAL_ELIGIBLE_ORIGINS = frozenset({"source"})

WEEK_MAX_TEMPORAL_HINTS = 500

METADATA_TEMPORAL_SIGNAL_VERSION = "temporal_signal_version"
METADATA_START_PRECISION = "start_precision"
METADATA_END_PRECISION = "end_precision"
METADATA_PARTICIPATION = "participation"
METADATA_PRIMARY_EVIDENCE_OBJECT_ID = "primary_evidence_object_id"
METADATA_EVIDENCE_COUNT = "evidence_count"
METADATA_EXTRACTION_CONFIDENCE = "extraction_confidence"
METADATA_SOURCE_REFERENCE_AT = "source_reference_at"
METADATA_SOURCE_SIGNATURE = "source_signature"
METADATA_EXTRACTOR_VERSION = "extractor_version"
METADATA_LIFECYCLE = "lifecycle"
METADATA_SUPERSEDED_BY_OBJECT_ID = "superseded_by_object_id"
METADATA_SEMANTIC_SUBJECT = "semantic_subject"
METADATA_PRIMARY_EVIDENCE_PROVIDER = "primary_evidence_provider"
METADATA_PRIMARY_EVIDENCE_KIND = "primary_evidence_kind"
