KIND_SCHEDULED_ACTIVITY = "scheduled_activity"

SCHEDULE_KIND_ONCE = "once"
SCHEDULE_KIND_DAILY = "daily"
SCHEDULE_KIND_WEEKLY = "weekly"
RECURRING_SCHEDULE_KINDS = frozenset({SCHEDULE_KIND_DAILY, SCHEDULE_KIND_WEEKLY})

SCHEDULED_ACTIVITY_STATUS_SCHEDULED = "scheduled"
SCHEDULED_ACTIVITY_STATUS_COMPLETED = "completed"
SCHEDULED_ACTIVITY_STATUS_CANCELLED = "cancelled"

SCHEDULED_ACTIVITY_STATUSES = frozenset(
    {
        SCHEDULED_ACTIVITY_STATUS_SCHEDULED,
        SCHEDULED_ACTIVITY_STATUS_COMPLETED,
        SCHEDULED_ACTIVITY_STATUS_CANCELLED,
    }
)

METADATA_SCHEDULE_KIND = "schedule_kind"
METADATA_PRIORITY = "priority"
METADATA_TIMEZONE = "timezone"
METADATA_LOCAL_TIME = "local_time"
METADATA_WEEKDAYS = "weekdays"

NOTIFICATION_PROPOSAL_TYPE = "scheduled_activity"
