DEFAULT_SYNC_DAYS = 14
MAX_SYNC_DAYS = 90
DEFAULT_MAX_CHANNELS = 50
MAX_MAX_CHANNELS = 100
DEFAULT_INITIAL_POSTS_PER_CHANNEL = 100
MAX_INITIAL_POSTS_PER_CHANNEL = 200
DEFAULT_MAX_POSTS_PER_RUN = 500
MAX_MAX_POSTS_PER_RUN = 1000
DEFAULT_SYNC_OVERLAP_SECONDS = 300
MAX_SYNC_OVERLAP_SECONDS = 3600

MATTERMOST_PROVIDER_SINCE_LIMIT = 1000
MATTERMOST_USERS_IDS_BATCH_SIZE = 200
MAX_MESSAGE_BODY_CHARS = 8000
MAX_TITLE_CHARS = 240
MAX_FILE_IDS_IN_METADATA = 20
MAX_MENTIONED_USER_IDS_IN_METADATA = 30
MENTION_ID_INSPECT_LIMIT = MAX_MENTIONED_USER_IDS_IN_METADATA + 1
