DEFAULT_IMAP_HOST = "imap.yandex.ru"
DEFAULT_IMAP_PORT = 993
DEFAULT_IMAP_TIMEOUT_SECONDS = 30
DEFAULT_SMTP_HOST = "smtp.yandex.ru"
DEFAULT_SMTP_PORT = 465
DEFAULT_MAIL_FOLDER = "INBOX"
DEFAULT_CALDAV_HOST = "caldav.yandex.ru"
DEFAULT_CALDAV_BASE_URL = "https://caldav.yandex.ru"

DEFAULT_SYNC_DAYS = 30
MAX_SYNC_DAYS = 90
DEFAULT_SYNC_LIMIT = 50
MAX_SYNC_LIMIT = 100

DEFAULT_CALENDAR_SYNC_DAYS_BACK = 60
MAX_CALENDAR_SYNC_DAYS_BACK = 90
DEFAULT_CALENDAR_SYNC_DAYS_FORWARD = 90
MAX_CALENDAR_SYNC_DAYS_FORWARD = 90
DEFAULT_CALENDAR_SYNC_LIMIT = 100
MAX_CALENDAR_SYNC_LIMIT = 100
MAX_CALENDAR_SYNC_CALENDARS = 10
LIVE_CALENDAR_LOOKBACK_DAYS = 1
CALENDAR_BACKFILL_SLICE_DAYS = 14
CALENDAR_BACKFILL_SLICE_OVERLAP_DAYS = 1
CALENDAR_BACKFILL_MIN_SLICE_DAYS = 1
CALENDAR_OPERATIONAL_QUERY_MAX_ITERATIONS = 500
MAX_YANDEX_FALLBACK_RECURRENCE_CANDIDATES = 256
MAX_YANDEX_FALLBACK_RECURRENCE_SCAN = 10000

CURRENT_YANDEX_CALENDAR_NORMALIZATION_VERSION = 2
CALENDAR_MULTIGET_BATCH_SIZE = 25

YANDEX_DISK_API_BASE = "https://cloud-api.yandex.net/v1/disk"
YANDEX_DISK_PROVIDER = "yandex_disk"
YANDEX_DISK_PUBLIC_RESOURCE_FIELDS = (
    "name,resource_id,type,created,modified,size,mime_type,md5,sha256,revision,public_url,path,media_type"
)

MAX_EMAIL_BODY_CHARS = 8000
MAX_EVENT_BODY_CHARS = 8000
