TEAMS_PROVIDER = "teams"
TEAMS_KIND = "chat_message"
TEAMS_ORIGIN = "source"
TEAMS_STATE = "observed"

CHAT_TYPE_ONE_ON_ONE = "oneOnOne"
CHAT_TYPE_GROUP = "group"
ACCEPTED_CHAT_TYPES = frozenset({CHAT_TYPE_ONE_ON_ONE, CHAT_TYPE_GROUP})

DIRECTION_INBOUND = "inbound"
DIRECTION_OUTBOUND = "outbound"

MESSAGE_TYPE_MESSAGE = "message"
MESSAGE_REFERENCE_CONTENT_TYPE = "messageReference"

OAUTH_STATE_TTL_MINUTES = 10
MICROSOFT_AUTHORITY = "https://login.microsoftonline.com/organizations"
MICROSOFT_AUTH_URL = f"{MICROSOFT_AUTHORITY}/oauth2/v2.0/authorize"
MICROSOFT_TOKEN_URL = f"{MICROSOFT_AUTHORITY}/oauth2/v2.0/token"
MICROSOFT_JWKS_URL = f"{MICROSOFT_AUTHORITY}/discovery/v2.0/keys"
MICROSOFT_ISSUER_PREFIX = "https://login.microsoftonline.com/"
MICROSOFT_ISSUER_SUFFIX = "/v2.0"
MICROSOFT_SIGNING_KEY_ISSUER_TEMPLATE = f"{MICROSOFT_ISSUER_PREFIX}{{tenantid}}{MICROSOFT_ISSUER_SUFFIX}"
GRAPH_API_BASE = "https://graph.microsoft.com/v1.0"
CONSUMER_TENANT_ID = "9188040d-6c67-4c5b-b112-36a304b66dad"
ID_TOKEN_LEEWAY_SECONDS = 30
AUTH_STATUS_ACTIVE = "active"
AUTH_STATUS_RECONNECT_REQUIRED = "reconnect_required"
MAX_RETRY_AFTER_SECONDS = 3600
DEFAULT_RATE_LIMIT_BACKOFF_SECONDS = 10

SCOPE_OPENID = "openid"
SCOPE_PROFILE = "profile"
SCOPE_OFFLINE_ACCESS = "offline_access"
SCOPE_USER_READ = "User.Read"
SCOPE_CHAT_READ = "Chat.Read"
SCOPE_CHAT_MESSAGE_SEND = "ChatMessage.Send"

TEAMS_OAUTH_SCOPES = [
    SCOPE_OPENID,
    SCOPE_PROFILE,
    SCOPE_OFFLINE_ACCESS,
    SCOPE_USER_READ,
    SCOPE_CHAT_READ,
    SCOPE_CHAT_MESSAGE_SEND,
]
REQUIRED_GRAPH_SCOPES = frozenset(
    {
        SCOPE_USER_READ,
        SCOPE_CHAT_READ,
        SCOPE_CHAT_MESSAGE_SEND,
    }
)

MAX_TITLE_CHARS = 240
MAX_MESSAGE_BODY_CHARS = 8000
MAX_DISPLAY_NAME_CHARS = 200
MAX_CHAT_TITLE_CHARS = 200
DEFAULT_SYNC_OVERLAP_SECONDS = 300
MAX_SYNC_OVERLAP_SECONDS = 3600
DEFAULT_MESSAGES_PAGE_SIZE = 50
MAX_MESSAGES_PAGE_SIZE = 50
DEFAULT_MAX_MESSAGE_PAGES_PER_CHAT = 20
MAX_MAX_MESSAGE_PAGES_PER_CHAT = 50
DEFAULT_MAX_CHAT_PAGES = 20
MAX_MAX_CHAT_PAGES = 50
TOKEN_REFRESH_SKEW_SECONDS = 60

SYNC_START_AT_KEY = "sync_start_at"
CHATS_STATE_KEY = "chats"
